### ISSUE TITLE
Cannot start the project

### ISSUE THREAD

**Issue by maciej-w** [robingenz/capacitor-firebase-plugin-demo#291]
**Describe the bug**
When I try to start the project on Android (real device or emulator) I get:
```
Process: dev.robingenz.capacitorjs.demo.firebaseplugins, PID: 6450
java.lang.RuntimeException: Unable to start activity ComponentInfo{dev.robingenz.capacitorjs.demo.firebaseplugins/dev.robingenz.capacitorjs.demo.firebaseplugins.MainActivity}: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process dev.robingenz.capacitorjs.demo.firebaseplugins. Make sure to call FirebaseApp.initializeApp(Context) first.
```

**To Reproduce**

1. Follow the instructions to start Android
2. In Logcat the above error appears

**Expected behavior**
App runs with no error

**Comment by robingenz** [comment]
You need to add the Firebase Configuration files. I updated the `Getting Started` section.
