### ISSUE TITLE
bug: npx ionic cap run ios unexpected output

### ISSUE THREAD

**Issue by StefanZivkovic** [robingenz/capacitor-firebase-plugin-demo#302]
**Describe the bug**
i have failed to start android app in android studio (screnshot 1). Also before that (screenshot 2), `npx ionic cap run android` prompts  with `Which device would you like to target?` while providing no options. Eventual result is `TypeError: Cannot read properties of undefined (reading 'value')`.

**To Reproduce**

1. npx ionic cap sync android - seems fine
2. npx ionic cap run android - not doing anything (screenshot 2)
3. open studio, try to run/build app, end up with errors
4. 

**Expected behavior**
`npx ionic cap run android` to actually do something. And then to hope that android studio can start the app

**Screenshots**
![image](https://github.com/robingenz/capacitor-firebase-plugin-demo/assets/44195291/f544394d-fedc-4abf-a628-87b1773fd56c)
![image](https://github.com/robingenz/capacitor-firebase-plugin-demo/assets/44195291/c8d42c98-fb72-42f5-804c-a4558b24dbf9)

**Desktop (please complete the following information):**

- OS: android
- Browser -
- Version 33/34

**Smartphone (please complete the following information):**

**Additional context**

**Comment by robingenz** [comment]
> Expected behavior
> npx ionic cap run ios to actually do something. And then to hope that android studio can start the app

„npx ionic cap run ios“ is only supported on MacOS since you need an installed version of XCode. I assume you use Ubuntu.

**Comment by StefanZivkovic** [comment]
Oh, its my mistype when i copy/paste for this issue. i have been doing `npx ionic cap run android`

**Comment by robingenz** [comment]
Okay, please take a look at this [SO answer](https://stackoverflow.com/a/38198021/6731412).

**Comment by StefanZivkovic** [comment]
OK, thanks for link. Can not look right now, will have to wait for later at the evening, or even tomorrow (or some other day)
